# Generated by Django 5.0.2 on 2024-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='triage_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
