# Generated by Django 5.0.2 on 2024-02-26 20:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('number_of_process', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('type_of_justice', models.CharField(choices=[('JEC', 'Jec'), ('CIVEL COMUM', 'Common Civil'), ('TRABALHISTA', 'Labor'), ('FEDERAL', 'Federal'), ('CRIMINAL', 'Criminal'), ('EXECUÇÃO FISCAL', 'Tax Enforcement')])),
                ('receive_by', models.CharField(choices=[('E-MAIL', 'Email'), ('ESAJ', 'Esaj'), ('PJE', 'Pje')])),
                ('date_time_of_treaty', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=255)),
                ('hearing_date', models.DateField()),
                ('preliminary_situation', models.CharField(choices=[('DEFERIDO', 'Granted'), ('INDEFERIDO', 'Rejected'), ('NÃO APRECIADA', 'Unappreciated'), ('NÃO HÁ LIMINAR', 'There Is No Injunction'), ('CUMPRIMENTO DE SENTEÇA', 'Enforcement Of Sentence')])),
                ('fatal_deadline', models.DateField()),
                ('obligation_to_do', models.TextField()),
                ('traffic_ticket', models.BooleanField()),
                ('value_of_the_fine', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_fine', models.CharField(choices=[('DIÁRIA', 'Daily'), ('ÚNICA', 'Only'), ('POR HORA', 'Hours'), ('POR ATOS', 'By Acts')], max_length=255)),
                ('judicial_determination', models.IntegerField()),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.modalidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RioDeJaneiroCeara',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('cpf_cnpj', models.CharField(max_length=20)),
            ],
            bases=('triage.triage',),
        ),
        migrations.CreateModel(
            name='SaoPaulo',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('quantity', models.IntegerField()),
                ('stamp_date', models.DateField()),
                ('internal_code', models.IntegerField()),
                ('value_of_the_claim', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('triage.triage',),
        ),
        migrations.AddField(
            model_name='triage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.state'),
        ),
    ]
