# Generated by Django 5.0.2 on 2024-02-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='state',
        ),
        migrations.DeleteModel(
            name='Modalidade',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
