# Generated by Django 5.0.2 on 2024-02-29 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_remove_triage_modalidade_remove_triage_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RioDeJaneiro',
            fields=[
                ('triage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='triage.triage')),
                ('cpf_cnpj', models.CharField(max_length=20)),
            ],
            bases=('triage.triage',),
        ),
        migrations.RenameModel(
            old_name='RioDeJaneiroCeara',
            new_name='Ceara',
        ),
    ]
