# Generated by Django 5.0.2 on 2024-03-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_riodejaneiro_rename_riodejaneiroceara_ceara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='preliminary_situation',
            field=models.CharField(choices=[('DEFERIDO', 'Granted'), ('INDEFERIDO', 'Rejected'), ('NÃO APRECIADA', 'Unappreciated'), ('CITAÇÃO / INTIMAÇÃO', 'Quote'), ('CUMPRIMENTO DE SENTEÇA', 'Enforcement Of Sentence')]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='receive_by',
            field=models.CharField(choices=[('E-MAIL', 'Email'), ('ESAJ', 'Esaj'), ('PJE', 'Pje'), ('PJE-RJ', 'Pje Rj'), ('SALESFORCE', 'Salesforce'), ('RDs', 'Rds'), ('DISTRIBUÍDOS', 'Distributed'), ('OUTROS', 'Others')]),
        ),
        migrations.AlterField(
            model_name='triage',
            name='type_of_justice',
            field=models.CharField(choices=[('JEC', 'Jec'), ('CIVEL COMUM', 'Common Civil'), ('TRABALHISTA', 'Labor'), ('FEDERAL', 'Federal'), ('CRIMINAL', 'Criminal'), ('EXECUÇÃO FISCAL', 'Tax Enforcement'), ('ACPs', 'Acps')]),
        ),
    ]
