# Generated by Django 5.0.2 on 2024-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_alter_saopaulo_quantity_alter_saopaulo_stamp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceara',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riodejaneiro',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='obligation_to_do',
            field=models.TextField(null=True),
        ),
    ]
