# Generated by Django 5.0.2 on 2024-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_alter_ceara_cpf_cnpj_alter_riodejaneiro_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceara',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riodejaneiro',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='saopaulo',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saopaulo',
            name='stamp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saopaulo',
            name='value_of_the_claim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='fatal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='judicial_determination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='obligation_to_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='type_of_fine',
            field=models.CharField(blank=True, choices=[('DIÁRIA', 'Daily'), ('ÚNICA', 'Only'), ('POR HORA', 'Hours'), ('POR ATOS', 'By Acts')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='value_of_the_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
