# Generated by Django 5.0.2 on 2024-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_alter_triage_fatal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='fatal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
