# Generated by Django 5.0.2 on 2024-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0009_alter_triage_fatal_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='value_of_the_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
