<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-12 20:02
=======
# Generated by Django 5.0.2 on 2024-03-12 12:05
>>>>>>> origin/main

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0011_triage_hearing_time_triage_procedural_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='hearing_time',
<<<<<<< HEAD
            field=models.TimeField(blank=True, null=True),
=======
            field=models.TimeField(),
>>>>>>> origin/main
        ),
        migrations.AlterField(
            model_name='triage',
            name='procedural_stage',
            field=models.CharField(choices=[('INGRESSADOS', 'Joined'), ('AVULSO', 'Loose')]),
        ),
    ]
