version: "3.12.1"

volumes:
    app_data:
        name: app_data
    app_broker:
        name: app_broker

services:
    django:
        image: apollo_system_api:development
        command: /bin/sh -c "apollo_system_api/docker/start.sh"
        depends_on:
            - postgres
        healthcheck:
            test: ["CMD", "pg_isready", "-h", "postgres", "-p", "5432"]
            interval: 5s
            timeout: 10s
            retries: 5
        env_file:
            - .env
        ports:
            - 8000:8000

    postgres:
        image: postgres:16.1
        volumes:
            - app_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: math@law
            POSTGRES_USER: postgres
            POSTGRES_DB: apollo_api
